---
- name: Print IP we're locking down to
  debug:
    msg: "{{ only_source_address }}"

- name: Value of revert_access
  debug:
    msg: '{{ revert_block }}'

- name: Allow me
  iptables:
    action: insert
    chain: INPUT
    source: "{{ only_source_address }}"
    protocol: tcp
    match: tcp
    jump: ACCEPT
    rule_num: 1
  become: true
  when: not revert_block

- name: Block everything else
  iptables:
    action: insert
    chain: INPUT
    jump: DROP
    rule_num: 2
  become: true
  when: not revert_block

- name: Revert block
  iptables:
    flush: true
    chain: INPUT
  become: true
  when: revert_block
