---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: apply-restriction
    box: centos/7
  - name: disable-restriction
    box: centos/7
provisioner:
  name: ansible
  inventory:
    host_vars:
      apply-restriction:
        host_to_apply_to: localhost
        only_source_address: "10.0.2.0/12"
      disable-restriction:
        host_to_apply_to: localhost
        only_source_address: "10.0.2.0/12"
        revert_block: true
        #  options:
        #    extra-vars: '{"host_to_apply_to":"localhost","only_source_address":"10.0.2.0/12"}'
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  enabled: true
  options:
    v: true
    sudo: true
  lint:
    name: flake8
    enabled: true
